const ezData=[
    {question:'Đọc số sau: 21 515',
        A:'Hai một năm một năm', 
        B:'Hai mươi một nghìn năm trăm mười năm',
        C:'Hai mươi mốt nghìn năm trăm mười lăm',
        D:'Hai mốt nghìn năm trăm mười lăm',
        answer: 3
        },
        {question:'Tập hợp các số tự nhiên khác 0 được kí hiệu là:',
        A:'',
        B:'{',
        C:'+',
        D:' *',
        answer: 4
        },
        {question:'Số tự nhiên nhỏ nhất là?',
        A:'0', 
        B:'1', 
        C:'2',
        D:'3', 
        answer: 1
        },
        {question:'Viết số sau: Hai tỉ hai trăm hai mươi hai triệu ba trăm chín mươi lăm nghìn năm trăm sáu mươi bảy.', 
        A:'2 222 395 567', 
        B:'2 202 395 567', 
        C:'2 000 395 567',
        D:'2 222 296 567', 
        answer: 1
        },
        {question:'Các số La Mã XV, XXI được đọc lần lượt là:', 
        A:'mười lăm, hai mốt',
        B:'mười năm, hai mốt',
        C:'mười lăm, hai mươi mốt',
        D:'mười bốn, mười chín',
        answer: 3
        },
        {question:'So sánh hai số 998 và 1 000 ta được:',
        A:'998 > 1 000',
        B:'998 < 1 000', 
        C:'998 = 1 000',
        D:'998 ≥ 1 000',
        answer: 2
        },
        {question:'Điền tiếp hai số tự nhiên vào dãy số sau để được dãy ba số tự nhiên liên tiếp tăng dần: 338; …; …',
        A:'337 và 336', 
        B:'339 và 338', 
        C:'339 và 340', 
        D:'340 và 342',
        answer: 3 
        },
        {question:'Điền tiếp hai số tự nhiên vào dãy số sau để được dãy ba số tự nhiên liên tiếp giảm dần: 1 256 ; …; …', 
        A:'1 257 và 1 258',
        B:'1 258 và 1 260',
        C:'1 255 và 1 253', 
        D:'1 255 và 1 254',
        answer: 4
        },
        {question:'Số tự nhiên lớn nhất là:', 
        A:'1 000 000 000',
        B:'100 000 000 000', 
        C:'999 999 999 999', 
        D:'Không có số tự nhiên lớn nhất',
        answer: 4
        },
        {question:'Số tự nhiên nhỏ nhất thuộc N*  là:',
        A:'0',
        B:'1',
        C:'2',
        D:'3',
        answer: 2
        },
        {question:'Cách viết tập hợp nào sau đây đúng?',
        A:'A = [1; 2; 3; 4]',     
        B:'A = (1; 2; 3; 4)',
        C:'A = 1; 2; 3; 4',     
        D:'A = {1; 2; 3; 4}',
        answer: 4
        },
        {question:'Cho B = {a; b; c; d}. Chọn đáp án sai trong các đáp án sau?',
        A:'a∈B', 
        B:'b∈B',
        C:'e∉ B', 
        D:'g ∈ B',
        answer: 4 
        },
        {question:'Cho B = {2; 3; 4; 5}. Chọn đáp án sai trong các đáp án sau?',
        A:'2 ∈ B',     
        B:'5 ∈ B',     
        C:'1 ∉ B',     
        D:'6 ∈ B',
        answer: 4
        },
        {question:'Cho M = {2; 3; b; c}. Chọn câu sai.',
        A:'3 ∈ M',
        B:'a ∉ M',
        C:'d ∈ M',
        D:'c ∈ M',
        answer: 3
        },
        {question:'Cho tập hợp A = {7; 8; 9}. Khẳng định nào sau đây là đúng?',
        A:'9  A',
        B:'78  A',
        C:'{8}  A',
        D:'{7; 9}  A',
        answer: 1
        },
        {question:'Cách viết tập hợp nào sau đây đúng?',
        A:'A = [2; 3; 5; 7]',     
        B:'A = (2; 3; 5; 7)',
        C:'A = 2; 3; 5; 7',
        D:'A = {2; 3; 5; 7}',
        answer: 4
        },
        {question:'Cho tập hợp A = {0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10}, phát biểu nào sau đây là đúng?',
        A:'11 ∈ A',
        B:'1 ∉ A',
        C:'7 ∉ A',
        D:'10 ∈ A',
        answer: 4
        },
        {question:'Cho tập M gồm các số tự nhiên lớn hơn 9 và nhỏ hơn 18, phát biểu nào sau đây là sai?',
        A:'12 ∈ M', 	
        B:'9 ∉ M', 	
        C:'18 ∈ M', 	
        D:'15 ∈ M', 
        answer: 3
        },
        {question:'Tập hợp Ν* là',
        A:'Tập hợp số tự nhiên',
        B:'Tập hợp các số tự nhiên khác 0',
        C:'Tập hợp các số tự nhiên lẻ',
        D:'Tập hợp các số tự nhiên chẵn',
        answer: 2
        },
        {question:'Cho tập hợp K = {0; 5; 3; 4; 7}. Tập hợp K có bao nhiêu phần tử?',
        A:'3',                       
        B:'4',                     
        C:'5',                              
        D:'2',
        answer: 3
        },
        {question:'Cách viết tập hợp dưới dạng liệt kê các phần tử là',
        A:'M = {1; 2; 3; 6; 7}',
        B:'N = x ∈ N; 9 < x < 15',
        C:'P = {x ∈ N*| x < 10}',
        D:'Q = 5; 6; 7; 8; 9',
        answer: 1 
        },
        {question:'Cách viết tập hợp dưới dạng nêu dấu hiệu đặc trưng cho các phần tử của tập hợp là',
        A:'M = {1; 2; 3; 6; 7}',
        B:'N = x ∈ N; 9 < x < 15',
        C:'P = {x ∈ N*| x < 10}',
        D:'Q = 5; 6; 7; 8; 9',
        answer: 3
        },
        {question:'Trong hai số tự nhiên a và b, nếu a lớn hơn b thì trên tia số nằm ngang điểm a nằm ở đâu?',
        A:'Bất kì trên tia số',
        B:'Bên phải điểm 0',
        C:'Bên phải điểm b',
        D:'Bên trái điểm b',
        answer: 3
        },
        {question:'Số liền trước và liền sau số 4 872 là',
        A:'Số liền trước là 4 873 và số liền sau là 4 871',
        B:'Số liền trước là 4 871 và số liền sau là 4 873',
        C:'Số liền trước là 4 781 và số liền sau là 4 783',
        D:'Số liền trước là 4 783 và số liền sau là 7 781',
        answer: 2
        },
        {question:'Cho hai số tự nhiên m = 58 741 và n = 58 475. Chọn đáp án đúng.',
        A:'m ≥ n',
        B:'m > n',
        C:'m < n',
        D:'m ≤ n',
        answer: 2
        },
        {question:'Cho số tự nhiên x, thỏa mãn 513 < x < 515.',
        A:'x = 512',
        B:'x = 514',
        C:'x = 516',
        D:'Không tồn tại x',
        answer: 2
        },
        {question:'Kí hiệu a  b có nghĩa là gì?',
        A:'a > b',
        B:'a = b',
        C:'a > b hoặc a = b',
        D:'a < b',
        answer: 3
        },
        {question:'Đọc số sau:  32 696',
        A:'Ba hai sáu chín sáu',
        B:'Ba hai sáu trăm chín mươi sáu',
        C:'Ba mươi hai nghìn sáu trăm chín mươi sáu',
        D:'Ba hai nghìn chín trăm sáu chín',
        answer: 3
        },
        {question:'Viết số 26 bằng số La Mã.',
        A:'XXVI',
        B:'XXVIII',
        C:'XXVII',
        D:'XXIV',
        answer: 1
        },
        {question:'Số La Mã IX biểu diễn cho số tự nhiên:',
        A:'4',
        B:'5',
        C:'14',
        D:'9',
        answer: 4
        },
        {question:'Hai mươi chín nghìn sáu trăm linh ba là số nào?',
        A:'29 603',
        B:'26 903',
        C:'23 609',
        D:'20 603',
        answer: 1
        },
        {question:'Biểu diễn các chữ số La Mã: XXI, XXII, XIX bằng các số tự nhiên lần lượt là:',
        A:'22; 21 và 19',
        B:'21; 22 và 19',
        C:'19; 21 và 22',
        D:'21; 19 và 22',
        answer: 2
        },
        {question:'Cho ba số tự nhiên a; 99 và 100. Biết rằng ba số đó là ba số liên tiếp nhau. Số tự nhiên a là:',
        A:'101',
        B:'98',
        C:'199',
        D:'Số tự nhiên nào cũng được',
        answer: 2
        },
        {question:'Trong các khẳng định sau, khẳng định nào sai?',
        A:'Số 1 là số tự nhiên nhỏ nhất',
        B:'Tập hợp các số tự nhiên có vô số phần tử',
        C:'Không có số tự nhiên lớn nhất',
        D:'Phần tử thuộc N nhưng không thuộc N* là 0',
        answer: 1
        },
        {question:'Viết các số sau theo thứ tự tăng dần: 34 087, 34 078, 43 089, 43 098.',
        A:'34 087, 34 078, 43 089, 43098',
        B:'34 078, 34 087, 43 089, 43 098',
        C:'34 078, 34 087, 43 098, 43 089',
        D:'34 087, 34 078, 43 098, 43 089',
        answer: 2
        },
        {question:'Giá trị của số 4 trong số 3457 là:',
        A:'4',			
        B:'4000',			
        C:'40',			
        D:'400',
        answer: 4
        },
        {question:'Tập hợp M các số tự nhiên lớn hơn hoặc bằng 3 và nhỏ hơn 9 được viết là:',         
        A:'M = {3; 4; 5; 6; 7; 8}',                     
        B:'M = {3; 4; 5; 6; 7; 8; 9}',
        C:'M = {3; 5; 7; 9}',                                                
        D:'M = {4; 5; 6; 7; 8}',
        answer: 1
        },
        {question:'Cho tập hợp A là tập các số tự nhiên nhỏ hơn hoặc bằng 7. Cách viết nào sau đây đúng.',
        A:'A = {0; 1; 2; 3; 4; 5; 6; 7}',
        B:'A = {0; 1; 2; 3; 4; 5; 6}',
        C:'A = {n ∈ N | n < 7}',
        D:'A = {n ∈ N* | n ≤ 7}',
        answer: 1
        },
        {question:'Viết lại tập hợp B = {1; 2; 3; 4; 5} bằng cách chỉ ra tính chất đặc trưng:',
        A:'B = {x  | x  5}',
        B:'B = {x  *| x  5}',
        C:'B = {x  *| x  5}',
        D:'B = {x  | x  5}',
        answer: 3
        },
        {question:'Nhận định nào sau đây sai?',
        A:'1  *',
        B:'0  *',
        C:'5  ',
        D:'8  ',
        answer: 3
        },
        {question:'Viết tập hợp A gồm các số tự nhiên lớn hơn 5 và nhỏ hơn 10.',
        A:'A = {6; 7; 8; 9}',     
        B:'A = {5; 6; 7; 8; 9}',
        C:'A = {6; 7; 8; 9; 10}',     
        D:'A = {6; 7; 8}',
        answer: 1
        },
        {question:'Biểu diễn mối quan hệ giữa 63 950 và 63 000 + 950?',
        A:'63 950 ≠ 63 000 + 950',
        B:'63 950 > 63 000 + 950',
        C:'63 950 < 63 000 + 950',
        D:'63 950 = 63 000 + 950',
        answer: 4
        },
        {question:'Cho m ∈ N*. Ba số tự nhiên liên tiếp tăng dần là:',
        A:'m - 2, m - 1, m',
        B:'m - 1, m , m + 1',
        C:'m + 1, m, m - 1',
        D:'m, m - 1, m - 2',
        answer: 2
        },
        {question:'Tập hợp K các số tự nhiên chẵn lớn hơn 11 và nhỏ hơn hoặc bằng 18 là:',
        A:'K = {12; 14; 16; 18}',
        B:'K = {12; 14; 16}',
        C:'K = {12; 13; 14; 15; 16; 17; 18}',
        D:'K = {11; 12; 13; 14; 15; 16;  17; 18}',
        answer: 1
        },
        {question:'Tìm các phần tử của tập hợp C, biết rằng C là tập hợp các số tự nhiên x sao cho x - 10 = 5',
        A:'C = {10; 15}',	
        B:'C = {10; 5}',	
        C:'C = ',	
        D:'C = {15}',
        answer: 4
        },
        {question:'Tập hợp các số tự nhiên được kí hiệu là:',
        A:' ',
        B:' ',
        C:' ',
        D:' ',
        answer: 1
        },
        {question:'Trong số 43 256 chữ số 3 nằm ở hàng nào?',
        A:'Hàng chục.',
        B:'Hàng trăm.',
        C:'Hàng nghìn.',
        D:'Hàng chục nghìn.',
        answer: 3
        },
        {question:'Cho  . a có thể là?',
        A:'240',
        B:'253',
        C:'235',
        D:'214',
        answer: 2
        },
        {question:'Một khu vườn trồng cam, táo, nho, bưởi. E là tập hợp các cây trồng trong khu vườn đó. Viết tập hợp E.',
        A:'E = {táo ; nho ; bưởi}',
        B:'E = {cam ; táo}',
        C:'E = {cam ; bưởi}',
        D:'E = {cam ; táo ; nho ; bưởi}',
        answer: 4
        },
        {question:'Tập hợp các số tự nhiên lẻ nhỏ hơn 5 là:',
        A:' ',
        B:' ',
        C:' ',
        D:' ',
        answer: 3
        },
        
]